title: Training Page
author: Sarah Johnson
email: sjohnson42@gmail.com
description: > # This is my trainng page. I'm using it for brainstorming, too.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
